### ISSUE TITLE
SC+ popup frequency

### ISSUE THREAD

**Issue by coty-crg** [SoundControl/Issues#100]
Can you please quit asking me for soundcontrol+ every goddamn time I open chrome? Thanks.I'm on edge of uninstalling because of how often it asks. I wouldn't mind it every other day or once a week. But every time I open chrome is way to much.

**Comment by SoundControl** [comment]
It should be every 3 days. I'll put in some extra checks to make sure it
isn't more. Also, please consider contributing; as little as $1 removes the
reminder.

**Comment by coty-crg** [comment]
You asking me to donate after the complaint I just did honestly made me uninstall it. 

Date: Wed, 29 Jan 2014 11:04:57 -0800

**Comment by SoundControl** [comment]
It takes work to maintain software. If you are getting software for free
(especially in the Chrome webstore) your web browsing is probably being
tracked and/or advertisements being injected into your webpages. I am
against these practices, so, yes, I ask for money -- good luck.
