### ISSUE TITLE
Volume starts completely down and seems to stay at 0 after muting the ads

### ISSUE THREAD

**Issue by KKIII** [SoundControl/Issues#103]
I think the subject covers it... (This means that I have to keep opening the Pandora page (I keep the tab hidden via SoundControl).

**Comment by SoundControl** [comment]
1) Please confirm that you are running v1.6 SoundControl
2) What version of Chrome are you running?
3) Please open the miniplayer and try to set the volume high and low. Does
it act as expected?

**Comment by KKIII** [comment]
1) - Verified 1.6
2) - Chrome version 33.0.1750.5m
3) - I have "triple-click" set to open the miniplayer. I had Pandora playing already, opened the miniplayer, the volume on the miniplayer was at "0" but the volume stayed at the current level until I clicked on the slider, it then dropped to zero until I slid it back up. I'm now waiting for a "mute event".
I'll add a coment after...

**Comment by SoundControl** [comment]
The source of this intermittent issue has been determined -- Thanks for your feedback.

**Comment by KKIII** [comment]
It seems to be working OK right now. Even after a restart of the browser. (I have not launched or looked at the miniplayer again).

**Comment by SoundControl** [comment]
1.6.1 will be available with the fix within the hour. Please let me know if you still experience any problems.
