### ISSUE TITLE
1.6 Changelog showing on ever start

### ISSUE THREAD

**Issue by allout58** [SoundControl/Issues#105]
The changelog for 1.6 is coming up every time I start Chrome. This isn't a major issue, but if very annoying.

**Comment by SoundControl** [comment]
I'm unable to duplicate the issue, but it sounds similar to a Chrome
settings saving bug. The solution to that is uninstalling/reinstalling
Google Chrome. Have you received the 1.6.1 update yet?

**Comment by allout58** [comment]
I did have the 1.6.1 version. I reinstalled SoundControl and that seems to have fixed whatever the problem was. Thanks!
