### ISSUE TITLE
Google Music, thumbs up/down doesn't fill or change state

### ISSUE THREAD

**Issue by megaroeny** [SoundControl/Issues#109]
The thumbs up/down works, but it would be nice if they actually filled in to let you know the click registered.

**Comment by SoundControl** [comment]
I'm unclear on what you mean. The thumbs up on the miniplayer does
highlight when a thumbs-up-ed song is playing. The thumbs down button
prompts the next song to be played, so the thumbs down generally doesn't
highlight.

Can you explain further?

**Comment by megaroeny** [comment]
Oh interesting. For me at the time thumbs up didn't highlight. I'll try again

~Reony
