### ISSUE TITLE
Spotify Album Cover notification

### ISSUE THREAD

**Issue by alicoding** [SoundControl/Issues#110]
Hello!

I love your extension and have to stop using my firefox sometime because your extension only available on Chrome.

I would like to request Spotify Album cover image on notification same like how you have it for Pandora if that is possible?

Thanks,
Ali

**Comment by SoundControl** [comment]
Thanks for reporting this bug. I'm looking into it now.

**Comment by alicoding** [comment]
Thanks!

**Comment by SoundControl** [comment]
The fix will be in the next update. When it is released, you'll have to
reselect Spotify in the options.
