### ISSUE TITLE
Set priority when more than one streaming source is currently open.

### ISSUE THREAD

**Issue by BusterNeece** [SoundControl/Issues#111]
Hello! I have often encountered an issue on the Soundcontrol plugin, wherein the following occurs:
- Pandora is open, playing music
- Open a YouTube video, click pause, it now pauses the YT video, leaving Pandora playing...

Or, the alternative happens:
- Pandora is open and paused
- Open a YT video, watch it completely
- Go to resume Pandora, and the YT video starts over instead.

I can imagine this is a tricky one from a development standpoint, but the only way I can imagine it really working from the user end is to have a "priority" user-ordered list, where the user specifies what they want to control more (in the event that more than one thing is open).Otherwise, the only way to resolve the issue is to turn off sites like YouTube until they're wanted again, which can be a hassle.

**Comment by SoundControl** [comment]
I'm not 100% clear on where you are saying a problem is. This behavior:
- Pandora is open, playing music
- Open a YouTube video, click pause, it now pauses the YT video, leaving
  Pandora playing

is intended. You can pause using the SoundControl button, which won't
auto-resume, or you can pause the youtube video directly, which resumes
Pandora.

As for this behavior:
- Pandora is open and paused
- Open a YT video, watch it completely
- Go to resume Pandora, and the YT video starts over instead.

This could be improved; for now you can see which player is activate by the
progress bar color on the button or use the miniplayer to select the active
player.
