### ISSUE TITLE
Songza integration

### ISSUE THREAD

**Issue by ryantreedy** [SoundControl/Issues#116]
'Songza offers playlists for activities such as waking up, working out, commuting, concentrating, unwinding, entertaining, and sleeping. Users can vote songs up or down, and the service will adapt to the user's personal music preferences. Users can find playlists not just based on artists, songs, or genres, but also based on themes, interests, and eras, such as "songs in Apple Commercials", "90s One-Hit Wonders", and "Music of Fashion Week".'

SoundControl support could allow the following actions from the Mini Player
-Pause, play, skip, and thumb up/down tracks
-Switch between saved playlists
-Browse for new playlists

**Comment by SoundControl** [comment]
Thanks, I will look into adding Songza soon

**Comment by SoundControl** [comment]
This will be in the next release
