### ISSUE TITLE
Thumb up Artist

### ISSUE THREAD

**Issue by ghost** [SoundControl/Issues#118]
Is it possible for you guys to integrate a "click-to-thumb-up-artist" (as opposed to just liking the track) option? That would be fantastic.

Thanks!

**Comment by SoundControl** [comment]
This is being considered, but low priority. Thanks

**Comment by Hugekase** [comment]
I agree with GamingBacon, I think it would be a wonderful idea, it would help us out a WHOLE lot, and get you guys more people.
