### ISSUE TITLE
Feature Request: Stitcher Support

### ISSUE THREAD

**Issue by Gilligan94** [SoundControl/Issues#121]
http://app.stitcher.com/

Stitcher is a podcasting platfrom. It has similar controls to Pandora (Play/Pause, Next, Thumb up and Thumb down http://puu.sh/8grCk/115236f8bd.png)

I would love to be able to control Stitcher with your wonderful app!

**Comment by SoundControl** [comment]
I've added it to the todo list -- Thanks!

**Comment by Gilligan94** [comment]
Awesome, can't wait!

**Comment by SoundControl** [comment]
In next version
