### ISSUE TITLE
Options page formatting, Integrate with

### ISSUE THREAD

**Issue by Gilligan94** [SoundControl/Issues#124]
the new All option doesn't appear to be in the right spot.

http://puu.sh/8A7GF/842546abf5.png

**Comment by Gilligan94** [comment]
![](http://puu.sh/8A7GF/842546abf5.png)

**Comment by SoundControl** [comment]
That is the YouTube on all pages check box. It is in the right place, but
it probably should be reworded.

**Comment by Gilligan94** [comment]
OOOH it all makes sense now, thanks.
