### ISSUE TITLE
SoundControl not working in latest version (v 35.0.1916.114 m) of Chrome 

### ISSUE THREAD

**Issue by btc9183** [SoundControl/Issues#127]
I am using Version 35.0.1916.114 m in Desktop mode on Windows 8.1 and the SoundControl extension is no longer working. I just updated to that version in an attempt to try and resolve the issue. Is anyone else having this problem or have any suggestions on how to resolve this? The icon for SoundControl just shows a puzzle piece 

![image](https://cloud.githubusercontent.com/assets/7647099/3030302/76dc46c0-e03f-11e3-92ff-6dc571d81f09.png)

and does nothing when I click on it. Thanks in advance for any help.

**Comment by SoundControl** [comment]
Sounds like your Chrome browser broke. I've heard reports of some
extensions getting deleted randomly by the browser. The only fix is
apparently to uninstall the extension, then reinstall it.

**Comment by btc9183** [comment]
I thought I did that already but apparently not because after uninstalling/reinstalling it is now working. Thanks for replying.

Bill
