### ISSUE TITLE
Add option to disable keyboard shortcuts if a site's not open

### ISSUE THREAD

**Issue by jorgenman** [SoundControl/Issues#128]
I use my media keyboard buttons to control SoundControl, but I'd also like to use them to control my local media player. The problem is that right now, when I press Play/Pause to pause my local media player, SoundControl opens up a Pandora page. Is there any way for SoundControl to recognize that I don't have Pandora (or anything else) open, and therefore not respond to the media button?

Thanks, and thanks for a great tool!

**Comment by SoundControl** [comment]
Not currently. There is a Chrome bug asking to allow this feature, but it
isn't looking like it will be improved soon.

Thanks for the feedback.
