### ISSUE TITLE
Stop after current

### ISSUE THREAD

**Issue by Keanomy** [SoundControl/Issues#133]
Hello.

I really do love the SoundControl app, however one thing i miss is a thing that i got in my other "local music player" or whatever you wanna call it, where i play mp3's.

That would be a way to make pandora play the song now playing till the end of the song and then stop playing/pause.

I haven't really given this that much thought other than it would be a great feature to be presented to SoundControl.

Agree/Disagree? 
Thoughts?

Sorry about potential bad english since it's my second language at best.

**Comment by SoundControl** [comment]
I've been thinking about that as a feature tied into an timed pause. For
example, set it to pause in 30 minutes. It would wait to the end of a song
and then pause around 33 minutes.

How did the interface for the program that you mention work? Was there a
dedicated button?

**Comment by Keanomy** [comment]
I'll give you a few images to describe how it works in my local mp3 player.

Doing this would make it play the song now playing and then stop.

![image](https://cloud.githubusercontent.com/assets/8218911/3640676/2c56619c-10a7-11e4-8d9d-83bca9fa81fb.png)

![image](https://cloud.githubusercontent.com/assets/8218911/3640682/38a1fb8c-10a7-11e4-9f73-dd4b5a0dda51.png)

**Comment by SoundControl** [comment]
This has been added into the timer function.
