### ISSUE TITLE
Soundcloud

### ISSUE THREAD

**Issue by grkan13** [SoundControl/Issues#135]
Hello, Soundcontrol is my main extension for chrome while working, totally a time-saver but since Soundcloud changed their layout and player, soundcontrol is not working on soundcloud.com. Is there anything to do on my side or do you need to update soundcontrol for the new changes?

Thank you very much for your hardworking.

**Comment by SoundControl** [comment]
I'm looking at it now

**Comment by SoundControl** [comment]
Their new interface is currently rather buggy. Expect an update that will
support it by tomorrow sometime.

**Comment by grkan13** [comment]
Thank you, that would be awesome

**Comment by grkan13** [comment]
Thanks man, you re the best :+1:
