### ISSUE TITLE
Pause timer?

### ISSUE THREAD

**Issue by megaroeny** [SoundControl/Issues#136]
I'm trying to figure out how the Pause Timer works... I understand the timer aspect. What does the second drop down do? Immediate vs Song End?

So let's say I select, Pause & Song End. What would that do? Another example; 20 minutes & Immediate.

![screen shot 2014-08-05 at 10 31 03 am](https://cloud.githubusercontent.com/assets/1559447/3812742/2a914da6-1cad-11e4-9d5a-96f5e125b33e.png)

Thanks!

**Comment by SoundControl** [comment]
Yeah, it could do with better instructions and wording. The first drop down
specifies how long until the timer is triggered. "Pause" is 0 minutes. The
second drop down specifies what to do when the timer is triggered.
"Immediate" will pause when it is triggered. "Song End" will wait until the
end of the song to pause.

**Comment by megaroeny** [comment]
Ah ok!! Thank you
