### ISSUE TITLE
Any way for notifications to pop up in a different corner of the screen? 

### ISSUE THREAD

**Issue by cfye14** [SoundControl/Issues#141]
subject line

**Comment by SoundControl** [comment]
No, unfortunately, Chrome doesn't currently allow for changing the corner
that the notifications display in.

**Comment by cfye14** [comment]
gotcha, thx

**Comment by cfye14** [comment]
What is the best way to pester google about this?

**Comment by SoundControl** [comment]
You could try voicing your opinion at http://crbug.com/301848

Although, I'm not sure how effective that would be. It would need to get
through the notifications UI team which currently seems to be paying more
attention to merging UI with Android.

**Comment by cfye14** [comment]
ok, thx
