### ISSUE TITLE
Can't switch to Spotify with Lite subscription

### ISSUE THREAD

**Issue by cfye14** [SoundControl/Issues#142]

**Comment by SoundControl** [comment]
I've just tested it and it is fully working for me. Can you explain further
how to recreate the issue and what the problem is?

**Comment by cfye14** [comment]
When I try to change my one web player from pandora to spotify, I see a pop-up telling me I need Plus to perform that action, basically.

**Comment by SoundControl** [comment]
Does the top of the page say "SoundControl Lite" or just "SoundControl"?

**Comment by cfye14** [comment]
It says SoundControl but I got a 1-month scrip on oct. 8 for lite. logged in to my browser.

**Comment by SoundControl** [comment]
It sounds like you may have uninstalled/reinstalled. To reactivate your
license key, go to Options > License > set license.

**Comment by cfye14** [comment]
when I go to License, I see a page for a Plus scrip. I have to paste a license key. 1] Am I on the right page? 2] Where would I find the license key?

**Comment by SoundControl** [comment]
The 'set license' button is on the bottom left of the license page. You
license key should have been emailed to you.

**Comment by cfye14** [comment]
I see the 'set license' button. However, I don't have any emails from soundcontrol with a license key, including in trash and spam folders. Do have email with transaction receipt, however.

**Comment by SoundControl** [comment]
Forward the receipt to me at scott@soundcontrolplus.com and I'll send you
your license key.
