### ISSUE TITLE
mini player not properly loading

### ISSUE THREAD

**Issue by dan-fern** [SoundControl/Issues#145]
I have the one click mini-player set to pop up with song info, station info, etc.  It never properly loads anymore.  That is to say that it did, and didn't require me to go to pandora.com at all.  Now, I have to go to pandora everytime to change the station.  Frustrating, because this was one of the better features of this extension.

**Comment by SoundControl** [comment]
I can't duplicate the issue that you are describing. Can't you provide more
details about what is going wrong?

I have set the miniplayer to one-click. It still works and I can choose the
station.

You may try restarting Chrome

**Comment by dan-fern** [comment]
I reinstalled and it seems to be working fine.
