### ISSUE TITLE
clicking on soundcontrol pops open a new pandora tab?

### ISSUE THREAD

**Issue by wpcprez** [SoundControl/Issues#29]
I'm not sure what happened but now my sound control won't do anything. The most it does is when you click it it opens a pandora tab. If you click it again it just opens another pandora tab next to the first one.

**Comment by SoundControl** [comment]
Did you reinstall or wait a couple hours for it to autoupdate like the extension page suggests? This bug is already fixed.

**Comment by wpcprez** [comment]
I've tried but I'll re-install again.

On 5/20/13, SoundControl notifications@github.com wrote:

> Did you check reinstall or wait a couple hours like the extension page
> suggests? This bug is already fixed.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/SoundControl/Issues/issues/29#issuecomment-18162423

## 

Johnny

**Comment by wpcprez** [comment]
I tried re-installing. This has actually been happening since last week. I also noticed when I go to the options page all of the options say "cancel mini player" and when I change them and go back into the options it still says "cancel mini player" on all of the options. Could this be related to me running chrome dev channel?

**Comment by dead-claudia** [comment]
I gave a few of my thoughts on this bug [here](https://github.com/SoundControl/Issues/issues/30) with a bit of extra detail that I had noticed as of lately, but as I tried to make clear in that (and is the sole reason why I'm not making a pull request) is that I am not really familiar with the Chrome API nor JavaScript, which I know there is a lot of in it.

On a side note, I do have a question of some importance in my opinion: how do you add labels to your own created issues? I can't seem to find that anywhere in the help.

**Comment by SoundControl** [comment]
@wpcprez You may be experiencing issue #7. It is possible that there was a bug in chrome's settings saving mechanism in the dev channel that corrupted your save data. I plan to make it easier for you to send me an error report and then get back to you.

Can you confirm that you are using 0.94.4? Are you still having all the same symptoms? 

@impinball You can't. See http://stackoverflow.com/questions/13829466/how-to-put-a-label-on-an-issue-in-github

**Comment by dead-claudia** [comment]
@SoundControl, I double-checked that the correct version, and even saw it in the extension itself displayed in the UI. I still had all of the symptoms of it, even after making that check. To me, though, it does feel like a piece of missing code, as I detailed in  #30. I am curious how correct an about where it is, though. 

**Edit:** Nothing else that use has any issues when it comes to saving the settings.

**Comment by wpcprez** [comment]
I figured out how to fix this.

 I went to my

C:\Users\username\AppData\Local\Google\Chrome\User Data\Default\Sync App
Settings folder

then deleted the subfolder that was my settings

then went to

C:\Users\username\AppData\Local\Google\Chrome\User Data\Default\Sync
Extension Settings

then deleted the subfolder that was my settings

upon restart of chrome everything worked as it did in the past.

Johnny

**Comment by SoundControl** [comment]
Thanks for the report!

@impinball I would appreciate it if you could wait to do this, as it destroys the evidence to debug it. I will post some reporting instructions soon.

**Comment by SoundControl** [comment]
@impinball Please:
1) go to chrome://extensions/?id=dckjilenognecmpjjpeckgekikdpchli
2) click developer mode in the upper left
3) click "_generated_background_page.html" under the SoundControl extension
4) click the Console tab in the upper right
5) run this code in the console:
chrome.storage.sync.get(null,function(a){console.log(JSON.stringify(a))});chrome.storage.local.get(null,function(a){console.log(JSON.stringify(a))})
6) copy-paste the output here

Also, what version of Chrome are you using?

**Comment by wpcprez** [comment]
{"id":"i4427535245195031","installed":1369156074686,"playing":[]}
bg.js:18chrome-extension://dckjilenognecmpjjpeckgekikdpchli/js/bg.js
1. storage.get: Failed to open database: Corruption: 4 missing files;
   e.g.: .../000016.sst at
   chrome-extension://dckjilenognecmpjjpeckgekikdpchli/js/bg.js:22:73chrome-extension://dckjilenognecmpjjpeckgekikdpchli/js/bg.js
   lastError:29 chrome-devtools://devtools/lastError
   1. setlastError:29 chrome-devtools://devtools/lastError

Uncaught TypeError: Cannot read property 'clickset' of undefined
bg.js:22chrome-extension://dckjilenognecmpjjpeckgekikdpchli/js/bg.js
 Array[2]
bg.js:25 chrome-extension://dckjilenognecmpjjpeckgekikdpchli/js/bg.js
 Array[2]
bg.js:25 chrome-extension://dckjilenognecmpjjpeckgekikdpchli/js/bg.js

Chrome Version 28.0.1500.11 m

Sorry, I didn't see your request to not delete the folders but I restored
them from my recycle bin and the problem reoccurred. So here's the debug
output. I will leave it broken till you tell me otherwise.

Johnny

**Comment by wpcprez** [comment]
Sorry that email came out horribly, here's from the web interface of github

{"id":"i4427535245195031","installed":1369156074686,"playing":[]} bg.js:18
storage.get: Failed to open database: Corruption: 4 missing files; e.g.: .../000016.sst
    at chrome-extension://dckjilenognecmpjjpeckgekikdpchli/js/bg.js:22:73 lastError:29
set lastError:29
Uncaught TypeError: Cannot read property 'clickset' of undefined bg.js:22
Array[2]
 bg.js:25
Array[2]
 bg.js:25

Chrome Version 28.0.1500.11 m Sorry, I didn't see your request to not delete the folders but I restored them from my recycle bin and the problem reoccurred. So here's the debug output. I will leave it broken till you tell me otherwise. 
Johnny

**Comment by SoundControl** [comment]
This looks a lot like a dev channel bug, especially since the last release was a week ago, May 14th. But it could still be due to the file restore. Please run:

chrome.storage.sync.get(null,function(a){console.log(JSON.stringify(a))});chrome.storage.local.get(null,function(a){console.log(JSON.stringify(a))});console.log(localStorage.sync,localStorage.local);

and paste the output. Thanks for your help.

**Comment by wpcprez** [comment]
chrome.storage.sync.get(null,function(a){console.log(JSON.stringify(a))});chrome.storage.local.get(null,function(a){console.log(JSON.stringify(a))});console.log(localStorage.sync,localStorage.local);
{"clickset":["playpause","popup","closepopup"],"songnotify":3,"listening":true,"hidetab":false,"pintab":true,"artbutton":false,"bigart":false,"advolume":0,"autoplay":true,"closereview":true,"version":"0.94.4","autocontinue":["pandora"],"ignoreautopause":[],"started":{"i5974766772706062":1368656057262,"i7023769754450768":1367877248062,"i8356479580979794":1368045676439,"i8556974264793098":1368952684675},"firstinstalled":1367877247995} {"id":"i4427535245195031","installed":1369156074686,"playing":["pandora"]}
undefined
storage.get: Failed to open database: Corruption: 4 missing files; e.g.: .../000016.sst lastError:29
undefined
{"id":"i4427535245195031","installed":1369156074686,"playing":["pandora"]}

**Comment by dead-claudia** [comment]
I got two lines of the "undefined" string, and the current version of the build I'm using is 27.0.1453.81 (beta channel).

**Comment by SoundControl** [comment]
@wpcprez Thanks. Definitely a chrome browser bug rather than a SC bug. I would suggest deleting your whole profile (The "Default" folder) to fix things, but you may be fine just deleting the files you did earlier.

@impinball No errors or data? What browser version are you using?

**Comment by wpcprez** [comment]
done thanks

**Comment by dead-claudia** [comment]
27.0.1453.81 (Official Build 198567) beta-m (copied straight from about:version)

**Comment by SoundControl** [comment]
Thanks. There is something very wrong with your browser if you are only
seeing 2 "undefined"s and no data or other errors. I suggest that you
reinstall the browser.

**Comment by dead-claudia** [comment]
I'm aware that it's closed, but the reinstall did nothing.

**Comment by dead-claudia** [comment]
And after the reinstall, I do have some different things showing up. With the first request, I have the following:
`chrome.storage is not available: You do not have permission to access this API. Ensure that the required permission or manifest property is included in your manifest.json. binding:202
TypeError: Cannot read property 'sync' of undefined`

**Comment by SoundControl** [comment]
Are you using "Google Chrome" or something else?

**Comment by dead-claudia** [comment]
I'm using it on Chrome...if not, I would've already made that clear.
