### ISSUE TITLE
I think something just isn't starting in this program... (or multiple things)

### ISSUE THREAD

**Issue by dead-claudia** [SoundControl/Issues#30]
**The problem:**
My settings will not save, and when I start Pandora through it, the tab doesn't show as having a script running on it like it usually does. The extension opens Pandora like it's supposed to, but no other part will do anything with that newly opened tab. I've tried reloading, re-installing, and neither (after multiple attempts at each one) will remedy the problem.

**My ideas as to what could be the cause of the problem:**
It feels like a portion of the program isn't running, because of the fact that Chrome isn't showing any scripts as running in the Pandora tab opened by the extension. It is probably breaking early without an error message, from the way this problem feels to me. A separate, but similar situation with the settings saving is what it seems to be with the lack of a link to load the settings already existing (while in the settings "editor" and during runtime). If the loading and running of these scripts are in the same area, then this bug would likely be a fairly simple and easy fix. I wish I knew a bit about JavaScript and the Chrome API, so I could make a fix myself.

**Comment by SoundControl** [comment]
What you're describing sounds like a combination of exactly #29 (which was fixed in the last update) Can you confirm that the extension shows up as version 0.94.4 in the extensions page?

It also seems to have some of #7 mixed in. I'm stilling working on figuring this one out. I think it happens when you are behind in extension updates.

**Comment by wpcprez** [comment]
yes I am using 94.4 (confirmed on extensions page). I even tried removing it and reinstalling it a few times.

**Comment by SoundControl** [comment]
Merged to #29
