### ISSUE TITLE
Suggestion - Clickable Song Notification

### ISSUE THREAD

**Issue by gallaghers** [SoundControl/Issues#31]
I find myself wanting to click on the Song Notification pop-up expecting that it will do something - though what, I'm not sure. Perhaps drop me into Pandora to see more about the artist/song. Perhaps it would be configurable as are the clicks on the mini-player.

Nice Chrome Extension!

**Comment by SoundControl** [comment]
I'm considering adding this configurability, but for now a click means: close the notification, in order to get it out of the way faster.

**Comment by katamari92** [comment]
Personally I like the click to close because I usually like what comes on pandora if i don't i'm usually too busy to get rid of it unless I REALLY don't like it. perhaps instead of coding it in you could give of a drop down of choices?

**Comment by SoundControl** [comment]
moving to #39
