### ISSUE TITLE
Randomly skipping tracks

### ISSUE THREAD

**Issue by supadave810** [SoundControl/Issues#36]
Songs seem to be randomly skipped. 
- They are not thumbed down, it appears just "next track / skip" button is being activated.
- This has happened on multiple songs at various points in the songs.
- This has happened with the 'Skip "Still Listening" feature enabled and disabled. 
  - I first noticed this issue with the 'Skip "Still Listening" enabled and thought that was causing it. I have disabled the feature and it still happens.

I have a paid Pandora subscription if it matters.

**Comment by SoundControl** [comment]
Do you have a process that can reliably duplicate the issue?
I have thought that I've seen this before, but then it turned out to be a poorly cropped song on Pandora's side.

**Comment by supadave810** [comment]
No I don't. It's just playing in the background. I'll try to see if there's anything I'm doing that is triggering it.

I know it's not poorly cropped songs (maybe sometimes) because it will happen sometimes in the first minute of a song, or on songs I've heard before.

**Comment by supadave810** [comment]
So I've noticed it once today when I just reading an article. No keyboard or mice actions. I may have scrolled shortly before it skipped.

**Comment by SoundControl** [comment]
Before SoundControl did you notice messages saying that Pandora had messed up and to click the Reload link to continue listening? SoundControl automatically reloads the page when this happens. I've created #41 in order keep track of whether this Pandora error is what is causing the skipping.

**Comment by supadave810** [comment]
I have received those errors in the past, but not yet with SoundControl.

**Comment by supadave810** [comment]
Had a few more skips today. Just doing random PC tasks. I was in Outlook cleaning up my inbox when the latest one skipped. The browser wasn't in focus.

Is there anything I can provide to help track this down?

**Comment by SoundControl** [comment]
After the next update comes out today or tomorrow, you can keep an eye out
for whether a notification pops up with an error message. Thanks for your
feedback!

**Comment by supadave810** [comment]
Ok, so I've disabled the extension and Pandora gives me the same issue. So, I don't think this is a SoundControl issue.

**Comment by SoundControl** [comment]
Great. Thanks. (Well, not so great for your system. I'd suggest looking
into a different version of flash)
