### ISSUE TITLE
Instructions for using keyboard shortcuts

### ISSUE THREAD

**Issue by SoundControl** [SoundControl/Issues#40]

**Comment by ghost** [comment]
Keyboard shortcuts are exactly why I'm trying out this extension as I want to be able to control Pandora with the media keys on my keyboard. Instructions for existing shortcuts would be fine; would be even better if we're able to set our own shortcuts to better use such keys.

**Comment by fewyun** [comment]
See #2. You can set custom shortcuts right now (but not media keys). Just go to Settings > Extensions > scroll to the bottom > Keyboard Shortcuts. Edit the SoundControl shortcuts.

**Comment by ghost** [comment]
O.o

Never realized that section even existed... thanks!

**Comment by SoundControl** [comment]
Exactly why there needs to be instructions! ;)

**Comment by SoundControl** [comment]
In the next version
