### ISSUE TITLE
Specify Number of Seconds to show Song Notifications

### ISSUE THREAD

**Issue by chrisatanasian** [SoundControl/Issues#44]
Add the functionality to allow the user to manually input how long he/she wants the song notification to be up for. Should allow any real number between 0 and x, where x is some reasonably large number.

**Comment by SoundControl** [comment]
I'm not currently planning on doing this from a usability perspective. Can
you provide a use case for the time you want?

**Comment by chrisatanasian** [comment]
Say the user wanted something above 5 seconds and below 10 seconds. They could start with 7.5 seconds and see how they liked it and then move up or down accordingly.

I'd probably want a time around 6 or 7 seconds myself.

**Comment by SoundControl** [comment]
A release has been pushed out with 7s. I'm considering using a slider bar input rather than a select box to handle more values.
