### ISSUE TITLE
Blank Updates and Option Tabs - Sound Control Won't Launch

### ISSUE THREAD

**Issue by LinuxNewb27** [SoundControl/Issues#48]
_EDIT_
I'm on Chrome 27.0.1453.116 and after I log in to Pandora I click on the SoundControl icon and it launches an Updates tab and then Pandora again. I don't get the pop out notification or anything. If I right-click the SoundControl icon I get a blank Options tab.

SoundControl shows v1.0 in my extension manager. Here are the pictures of no settings

![image](https://f.cloud.github.com/assets/4732566/671600/9bc3b1ae-d860-11e2-8f7b-707840c88e40.png)

I removed SoundControl through the extension manager and then I deleted the 2 leftover folders. I also went in to Chrome and removed cache and plug-in data. I restarted Chrome and now the player shows up when I double-click the icon. I can't get the notification window to pop up though... I will keep looking in to it.
![image](https://f.cloud.github.com/assets/4732566/671723/3bfa9c0c-d864-11e2-86ba-5f1970a9c376.png)

**Comment by SoundControl** [comment]
Yep base.css is blank. Your problem sounds a lot like a couple other users.
Their Chrome settings database were corrupted. One completely reinstalled
Chrome and the other deleted an appdata folder to get it working again. I
think you're on the right track.

**Comment by SoundControl** [comment]
Please post new comments so the thread can be followed. I expect it was corruption of the Sync Extension Settings. Are you saying that options now shows up correctly? It sounds like it is working. The notification won't show up if the miniplayer or pandora is focused.

**Comment by LinuxNewb27** [comment]
Correct, after I removed the folders and cleared the plug-in data from the Advanced Settings within Chrome, I re-installed the extension and was able to get the proper windows displayed (Update on first launch and Options).

Maybe this is a separate issue but it seems the notification window doesn't work all the time. When I got the extension back up, one of the first things I changed was that the notification window is always on. I went back to Pandora and skipped a station but the small notification window didn't come up. I exited Chrome, re-launched it w/Pandora and the window came up. I then clicked it to once to hide it and wasn't able to bring it back up, either by skipping the song or exiting Chrome. One thing I did not try was changing the notification window to another setting, exit, then back to the "always on", exit, and re-launch.

**Comment by SoundControl** [comment]
Good catch: the notification not showing up when it is set to always on and
Pandora is focused is a bug, but working as currently coded.

However, Google is screwing around with the notification API and I may not
be able to support always on in the first place. I'll check it out. It
sounds like you've at least got the corruption out of your system.
