### ISSUE TITLE
No pictures, no options page

### ISSUE THREAD

**Issue by pyzro** [SoundControl/Issues#49]
I've come across an issue after installing the extension- When I open the mini-player, there are no images (play, pause) and no playlist information. I get the playlist/options/tab links at the bottom, but there are more issues- Playlist and tab links don't actually do anything or go anywhere, and the option link opens a blank page.  I thought that maybe running adblock plus would be an issue, so I removed it as well as reinstalled soundcontrol. The "buttons" do not work (play/pause that should be in the middle of the mini player).  Clicking the soundcontrol icon in chrome only opens another pandora tab.

Chrome: Version 27.0.1453.116 m

Thanks for your time and effort.

**Comment by SoundControl** [comment]
Sounds like #48. Chrome storage corruption bug. If you reinstalled
SoundControl and there was still a problem, then the problem is in Chrome,
not SoundControl. I suggest reinstalling Chrome.
