### ISSUE TITLE
Pandora keeps crashing

### ISSUE THREAD

**Issue by 3litetrooper** [SoundControl/Issues#50]
Hey, so I've been using soundcontrol for awhile now and all of the sudden Pandora decides to crash when I have soundcontrol enabled. I'm using Chromium and am running Windows 7. I've tried re-downloading soundcontrol, but it still keeps causing Pandora to crash, but when I have it disabled, it works just fine. Weird, huh?

**Comment by SoundControl** [comment]
That is weird. I'll look into it. In the meantime, I suggest that you try upgrading (or downgrading) your version of flash.
