### ISSUE TITLE
Volume randomly changes

### ISSUE THREAD

**Issue by kswanquist** [SoundControl/Issues#51]
Every once in awhile, the volume on SoundControl will just go down, so I constantly have to keep going back into the app and bringing the volume back up. Otherwise, love the app and hooray for no commercials and continuous Pandora listening!

**Comment by SoundControl** [comment]
Do you have another extension that runs on Pandora? When the volume
randomly changes does it always go down? Always to zero? Always greater
than zero? What version of chrome and SoundControl are you using? When it
happens what are you doing on the computer?

**Comment by kswanquist** [comment]
I do not have any other extensions that run on Pandora.

When the volume changes, it goes lower...sometimes to zero, sometimes
greater than zero. I'm not positive on this, but it seems to happen after
SoundControl mutes commercials/ads. I don't always notice it right away
because I use it on my work computer so I may be doing something else
before I realize the music was turned down. When I get phone calls, I hit
the mute button on my speakers, but I've tested that and it doesn't seem to
have an effect. I have Chrome version 27.0.1453.116 m. I have SoundControl
version 1.0.2.

Thanks!

Kevin
