### ISSUE TITLE
upgrade missing

### ISSUE THREAD

**Issue by yassineS** [SoundControl/Issues#54]
hi,

I can't find the upgrade function in the config page of soundcontrol even after billing.

**Comment by SoundControl** [comment]
I show that you have been upgraded. Does the title show as SoundControl *
plus\* on the options page?

**Comment by yassineS** [comment]
It seems that it toke more time than supposed (like 15minutes) but it’s working now. Thank you for your help and for the excellent extension.

Keep the good job guys,

Yassine

**Comment by SoundControl** [comment]
Thanks!
