### ISSUE TITLE
Youtube Integration?

### ISSUE THREAD

**Issue by mpolichette** [SoundControl/Issues#56]
Hello,

I am glad to support your product. It does exactly what I was looking for.  The thing that pushed me over the edge to support was the youtube integration, but it doesn't seem to be working for me.  When I play a youtube video, the music doesn't pause. 

:/

I'd love to know what I'm doing wrong :)
Thanks,
Matt

**Comment by SoundControl** [comment]
When you open the SoundControl options page, does it say SoundControl _plus_
?

Does the icon control the youtube player?

Are you playing a youtube video from youtube.com or a different domain?

**Comment by mpolichette** [comment]
So it does say sound control plus and the Icon is not controlling the youtube player.  Is there a chance it would not work if I have plugins disabled by default? I have chrome set up so I have to click the video for it to load.

In content settings, under plug-ins, I have it set to "click to play."
chrome://settings/content 

Also, will the extension also pause when a youtube video is imbedded into another sites page?

**Comment by SoundControl** [comment]
I'll have to look into the plugin setting. It currently only works at
YouTube.com but support will be expanded to other pages.

**Comment by SoundControl** [comment]
Fixed in the next release
