### ISSUE TITLE
Just bought plus - Music not pausing when I play a youtube video

### ISSUE THREAD

**Issue by Tecm0** [SoundControl/Issues#60]
Note: I am using a userscript called Youtube Center to automatically set the quality to 720p. I don't know if that would interfere with sound control pausing pandora when they video starts.

I have already checked YouTube integrate box.

**Comment by SoundControl** [comment]
Where's the user script?
Are you at YouTube.com or another site?
Does the button work to control the YouTube player at all?

**Comment by Tecm0** [comment]
the userscript is from userscripts.org named "Youtube Center"

I am at youtube.com

the button doesn't do anything to youtube

isnt the pandora music supposed to pause automatically when i start playing a youtube video?

**Comment by Tecm0** [comment]
I tested it without the Youtube Center script and it pauses the music correctly. Is there any way to make it work with youtube center? I watch every video in 720p so it would be a pain to have to change the quality every time

**Comment by Tecm0** [comment]
http://userscripts.org/scripts/show/114002
theres the link for youtube center

**Comment by Tecm0** [comment]
I tried it with a few scripts that auto set the quality to HD and the integration doesn't work with any of them.

**Comment by Tecm0** [comment]
scratch that.. it was working earlier but after disabling any youtube scripts and testing it again it just wont work..
i tried it on both http://www.youtube.com/ and https://www.youtube.com/

**Comment by SoundControl** [comment]
I'm looking into the conflict. Auto-720p is a feature that I'm considering
adding as well

**Comment by Tecm0** [comment]
Good to know, and thanks a lot for this awesome extension!

**Comment by SoundControl** [comment]
Also, see #56

**Comment by SoundControl** [comment]
See #85
