### ISSUE TITLE
Icon Click Actions

### ISSUE THREAD

**Issue by MrDevanWright** [SoundControl/Issues#61]
When I set "Click 1 time" to open "Mini Player" clicking it again won't close the Mini Player, it just opens it again. How can I fix this?

Also, how can I set a Click option to open nothing? I wanted to set "Click 1 time" to nothing and then setup "Click 2 times" for something else. Every time I set the "Click 1 time" to nothing, it erases everything the actions after it.
I was only trying to set it up this way to circumvent the problem arising out of making the "Click 1 time" open the Mini Player.

Is it possible to make the "Click 1 time" option Open the Mini Player when closed and close the Mini Player when open?

Also, this extension is amazing. Thank You!

**Comment by SoundControl** [comment]
Revamping the click architecture to eliminate the click to cancel
miniplayer is on the todo list. The issue that you bring up will be
addressed at the same time.

What OS are you using?

**Comment by MrDevanWright** [comment]
I am on Windows 7 through Google Chrome Version 28.0.1500.72 m.

Thanks for having that on the to do list. I look forward to it.
I will definitely be getting Plus soon.

Thanks!

**Comment by SoundControl** [comment]
This should be improved as of 1.9.1
