### ISSUE TITLE
Autostart of Pandora Tab

### ISSUE THREAD

**Issue by ghost** [SoundControl/Issues#63]
Whenever I open Chrome, the Pandora tab open automatically. I don't want that, there must be an option to choose this feature. Furthermore, it'd be awesome if we can choose the start-up state of Pandora. As of now, the only available option is to remember the last state, how about an option to define start-up state to set it to play/pause regardless of last state.

Thank you. This app is awesome though.

**Comment by fragilerus** [comment]
overlaps with feature request #99

**Comment by SoundControl** [comment]
Indeed. This is on the short list. Tracking will continue on #99
