### ISSUE TITLE
Pause button doesnºt work

### ISSUE THREAD

**Issue by Digisolid-Root** [SoundControl/Issues#64]
Iºm using the extension for Pandora radio on Win7 x64 with Chrome Version 28.0.1500.95
Everything seems to work properly except the pause functionality when clicking the pause button.

**Comment by SoundControl** [comment]
What version of SoundControl are you using?

**Comment by Digisolid-Root** [comment]
I'm assuming is the latest one (1.0.3), just installed today from the web
store.

**Comment by SoundControl** [comment]
I'm unable to duplicate or find a reason for your issue. Can you give me
more information that may be unique to your setup? Otherwise, have you
tried reinstalling it?

**Comment by Digisolid-Root** [comment]
The issue is now gone!
I closed everything and opened again and the issue disappeared.
