### ISSUE TITLE
Not working - Controls don't work, options page blank, mini player blank

### ISSUE THREAD

**Issue by dhug** [SoundControl/Issues#65]
![chromeversion](https://f.cloud.github.com/assets/5349199/1060180/3826470a-11aa-11e3-86ed-7c7373a94b23.JPG)
![blankoptionspage](https://f.cloud.github.com/assets/5349199/1060181/38266a50-11aa-11e3-9a49-35dd804fc15a.JPG)
![miniplayer](https://f.cloud.github.com/assets/5349199/1060182/3827948e-11aa-11e3-8fdb-06a417da2746.JPG)

Extension isn't working at all.  When I press the button it just launches a new tab of Pandora but does nothing to control it.  When i launch the options, it just launched a new blank tab (see 1st image below).  Mini player is also blank when launched (2nd image below).  Can't get it to work for the life of me.  Chrome is up to date (see 3rd image below).  I've tried deleting cookies and plug-in data along with clearing the cache.  

Has anyone else had this problem or anyone know how to fix it?

![blankoptionspage](https://f.cloud.github.com/assets/5349199/1060144/6f2f2d76-11a9-11e3-85f4-fbdfe7d09b99.JPG)
![miniplayer](https://f.cloud.github.com/assets/5349199/1060143/6f30679a-11a9-11e3-9167-0987796e3ef4.JPG)
![chromeversion](https://f.cloud.github.com/assets/5349199/1060142/6f2d6f40-11a9-11e3-8588-1ca5c79205ba.JPG)

**Comment by fewyun** [comment]
What version of SoundControl are you running?

It looks like #48 which is a Chrome bug. (Usually caused by a system restore, did you recently do a system restore?) If it is, you have to delete your Chrome profile or completely reinstall Chrome.

**Comment by dhug** [comment]
Yes, I did just recently do a system restore.  Thank you for the quick reply.  Deleting the Chrome profile took care of the issue and it's working fine now.
