### ISSUE TITLE
Hide Pandora Tab not working

### ISSUE THREAD

**Issue by cabradio** [SoundControl/Issues#68]
Hide Pandora is not working. I click on the option to hide, Pandora stops momentarily, the Pandora tab closes, then when it restarts the tab reopens. Please advise. Thanks!

**Comment by SoundControl** [comment]
Are you logged into Pandora?

**Comment by cabradio** [comment]
Yes.

**Comment by SoundControl** [comment]
Do you have plug-ins set to "play-on-click"? I have just found that that setting does cause the symptom that you are describing.

**Comment by cabradio** [comment]
Yes, I have it to play on one click. Should I change it to 2 clicks and set
1 click to do nothing?

**Comment by SoundControl** [comment]
I didn't communicate my question completely. When you play flash plugins in Chrome (like flash games) does you have to click a gray box to start it playing or does the flash plugin automatically start?

Are plugins set to "run automatically" at this settings page? --> chrome://settings/content

**Comment by cabradio** [comment]
Oh, no.. set to "Run Automatically"

**Comment by SoundControl** [comment]
It wasn't set to automatic, but it is now? So, does it work now?

I have found that you can either set it to Run Automatically or add "chrome-extension://dckjilenognecmpjjpeckgekikdpchli/" as an exception to fix this problem.

This problem is fixed now?

**Comment by cabradio** [comment]
No, was already set to automatic. Problem still exists. Closed all
browsers, restarted laptop. Opened Chrome, clicked Sound Control to start
Pandora, and Pandora still opened in new tab.

**Comment by SoundControl** [comment]
What are your OS, OS version, SoundControl version, Chrome version?

**Comment by cabradio** [comment]
Windows 7 home premium service pack 1
Sound Control 1.1
Chrome Version 29.0.1547.66 m

**Comment by cabradio** [comment]
Chrome just updated to Version 29.0.1547.76 m
I will check to see if that fixes the issue.

**Comment by cabradio** [comment]
Right now, the first instance I click Sound Control after starting up my laptop, and opening the browser causes a Pandora tab to open. But when I close the browser and open again, click on Sound Control play, the Pandora tab does not open.

**Comment by SoundControl** [comment]
Interesting. Do you have many tabs open? Do you have the browser set to
open the last tabs on startup?

**Comment by cabradio** [comment]
No, not many tabs usually...maybe 3-4? (what is many? haha) Browser is not set to open last tabs... opens Chrome most visited pages.

**Comment by cabradio** [comment]
It seems to be functioning properly now. Most likely was that Chrome needed to update. Thanks for your help! I also like how with the Premium version the player pauses for YouTube, etc. Very cool. Although, while a YouTube ad is playing, the Sound Control does not pause until the ad is over and the actual video starts...
