### ISSUE TITLE
Settings sometimes won't save

### ISSUE THREAD

**Issue by SoundControl** [SoundControl/Issues#7]
I think this is a firewall/connection issue. Make it more resilient.

**Comment by SoundControl** [comment]
waiting for more error information

**Comment by katamari92** [comment]
Issue #29 This happened to me when chrome files were currupted I had to reinstall chrome to fix this.

**Comment by SoundControl** [comment]
This has proven to be Chrome settings corruption in every case so far. I suggest reinstalling Chrome or deleting the settings folders from your Chrome profile and restarting.
