### ISSUE TITLE
SoundCloud Support

### ISSUE THREAD

**Issue by nvgrw** [SoundControl/Issues#70]
I'd like to see SoundCloud support in SoundControl (Plus?).

Thanks!

**Comment by nvgrw** [comment]
Never mind, it just appeared on my settings page.

**Comment by SoundControl** [comment]
It is. Check the options. Do you see it?

**Comment by nvgrw** [comment]
Yeah I do see it, I already closed the issue.
Thanks for continually improving SoundControl :+1:
