### ISSUE TITLE
Recent Chrome Update Issue: Sound Control Plus upgrade gone

### ISSUE THREAD

**Issue by njsurfrgurl** [SoundControl/Issues#71]
During the most recent chrome update (Current Chrome Version 29.0.1547.76 m), it seems that my Sound Control Plus upgrade went away. I tried to remove the extension and then re-install to see if this would resolve  my issue but alas it didn't.
I'm fine with donating again to regain my Plus upgrade but I also wanted to bring it to your attention so that if and when it becomes a service which you sell, others do not lose their access due to Chrome updating.
Is there another solution I should attempt?
I love the extension and the Plus upgrade...keep the updates coming!
Thanks,
Jess

**Comment by SoundControl** [comment]
The Chrome update shouldn't have caused a problem. Can you provide any more
information? Had you recently done a System Restore?

Uninstalling the extension, however, does cause you to lose the plus
upgrade. I've been restoring accounts on a case-by-case basis, but there
will be an automated restoration mechanism in the near future.
