### ISSUE TITLE
soundcontrol plus upgrade didn't worked

### ISSUE THREAD

**Issue by ghost** [SoundControl/Issues#73]
hello!

i payed via paypal for the plus upgrade. i also got the email with the license key, but the app didn't upgraded. it still says, that i should buy the plus upgrade.

can anyone help me??

**Comment by nickelob** [comment]
Donated for the plus upgrade as well.  Still haven't received the plus upgrade either.

**Comment by SoundControl** [comment]
I have followed up with everyone that has been confused about the plus upgrade process through email.
