### ISSUE TITLE
Just purchased upgrade but I can't get the download

### ISSUE THREAD

**Issue by pcbeltz** [SoundControl/Issues#75]
Transaction info:  Oct 6, 2013 15:01:23 PDT
Transaction ID: 55S41740G46166845
Thanks,
Paul

**Comment by SoundControl** [comment]
Paul, you contributed less than the threshold for a plus upgrade. Thanks

**Comment by pcbeltz** [comment]
It never said that on your website, that¹s lame.  Can you point it out?  Is
the threshold $8?

From:  SoundControl notifications@github.com
Reply-To:  SoundControl/Issues
<reply+i-20587070-4426215101f18fef80dc28ef9ae7bda9fef0d030-5624824@reply.git
hub.com>
Date:  Sunday, October 6, 2013 3:32 PM
To:  SoundControl/Issues Issues@noreply.github.com
Cc:  Paul Beltz pcbeltz@gmail.com
Subject:  Re: [Issues] Just purchased upgrade but I can't get the download
(#75)

Paul, you contributed less than the threshold for a plus upgrade. Thanks

‹
Reply to this email directly or view it on GitHub
https://github.com/SoundControl/Issues/issues/75#issuecomment-25778445 .

**Comment by SoundControl** [comment]
When you slide the slider below $3, SoundControl plus disappears from the
"You'll get" list of benefits.

Was this not clear to you?

**Comment by pcbeltz** [comment]
No, I’ll donate another $1 if I can get it to work, okay?  Perhaps more in
the future?  Thanks, Paul

From:  SoundControl notifications@github.com
Reply-To:  SoundControl/Issues
<reply+i-20587070-4426215101f18fef80dc28ef9ae7bda9fef0d030-5624824@reply.git
hub.com>
Date:  Sunday, October 6, 2013 3:42 PM
To:  SoundControl/Issues Issues@noreply.github.com
Cc:  Paul Beltz pcbeltz@gmail.com
Subject:  Re: [Issues] Just purchased upgrade but I can't get the download
(#75)

When you slide the slider below $3, SoundControl plus disappears from the
"You'll get" list of benefits.

Was this not clear to you?

On Sun, Oct 6, 2013 at 5:34 PM, pcbeltz notifications@github.com wrote:

> It never said that on your website, that¹s lame. Can you point it out? Is
> the threshold $8?
> 
> From: SoundControl notifications@github.com
> Reply-To: SoundControl/Issues
> 
> <reply+i-20587070-4426215101f18fef80dc28ef9ae7bda9fef0d030-5624824@reply.git
> hub.com> 
> Date: Sunday, October 6, 2013 3:32 PM
> To: SoundControl/Issues Issues@noreply.github.com
> Cc: Paul Beltz pcbeltz@gmail.com
> Subject: Re: [Issues] Just purchased upgrade but I can't get the download
> (#75) 
> 
> Paul, you contributed less than the threshold for a plus upgrade. Thanks
> 
> ‹ 
> Reply to this email directly or view it on GitHub
> https://github.com/SoundControl/Issues/issues/75#issuecomment-25778445
> . 
> 
> — 
> Reply to this email directly or view it on
> GitHubhttps://github.com/SoundControl/Issues/issues/75#issuecomment-25778473
> . 

—
Reply to this email directly or view it on GitHub
https://github.com/SoundControl/Issues/issues/75#issuecomment-25778612 .

**Comment by SoundControl** [comment]
I've issued you a refund. Refunds cost me extra, please consider
contributing more. Thanks.

**Comment by pcbeltz** [comment]
Thanks!  Will do.

From:  SoundControl notifications@github.com
Reply-To:  SoundControl/Issues
<reply+i-20587070-4426215101f18fef80dc28ef9ae7bda9fef0d030-5624824@reply.git
hub.com>
Date:  Sunday, October 6, 2013 3:58 PM
To:  SoundControl/Issues Issues@noreply.github.com
Cc:  Paul Beltz pcbeltz@gmail.com
Subject:  Re: [Issues] Just purchased upgrade but I can't get the download
(#75)

I've issued you a refund. Refunds cost me extra, please consider
contributing more. Thanks.

On Sun, Oct 6, 2013 at 5:44 PM, pcbeltz notifications@github.com wrote:

> No, I’ll donate another $1 if I can get it to work, okay? Perhaps more in
> the future? Thanks, Paul
> 
> From: SoundControl notifications@github.com
> Reply-To: SoundControl/Issues
> 
> <reply+i-20587070-4426215101f18fef80dc28ef9ae7bda9fef0d030-5624824@reply.git
> hub.com> 
> Date: Sunday, October 6, 2013 3:42 PM
> To: SoundControl/Issues Issues@noreply.github.com
> Cc: Paul Beltz pcbeltz@gmail.com
> Subject: Re: [Issues] Just purchased upgrade but I can't get the download
> (#75) 
> 
> When you slide the slider below $3, SoundControl plus disappears from the
> "You'll get" list of benefits.
> 
> Was this not clear to you?
> 
> On Sun, Oct 6, 2013 at 5:34 PM, pcbeltz notifications@github.com wrote:
> 
> > It never said that on your website, that¹s lame. Can you point it out?
> > Is 
> > the threshold $8?
> > 
> > From: SoundControl notifications@github.com
> > Reply-To: SoundControl/Issues
> > 
> > <reply+i-20587070-4426215101f18fef80dc28ef9ae7bda9fef0d030-5624824@reply.git
> > hub.com> 
> > Date: Sunday, October 6, 2013 3:32 PM
> > To: SoundControl/Issues Issues@noreply.github.com
> > Cc: Paul Beltz pcbeltz@gmail.com
> > Subject: Re: [Issues] Just purchased upgrade but I can't get the
> > download 
> > (#75) 
> > 
> > Paul, you contributed less than the threshold for a plus upgrade. Thanks
> > 
> > ‹ 
> > Reply to this email directly or view it on GitHub
> > https://github.com/SoundControl/Issues/issues/75#issuecomment-25778445
> > 
> > . 
> > 
> > — 
> > Reply to this email directly or view it on
> > GitHub< 
> > https://github.com/SoundControl/Issues/issues/75#issuecomment-25778473>
> > . 
> 
> — 
> Reply to this email directly or view it on GitHub
> https://github.com/SoundControl/Issues/issues/75#issuecomment-25778612
> . 
> 
> — 
> Reply to this email directly or view it on
> GitHubhttps://github.com/SoundControl/Issues/issues/75#issuecomment-25778640
> . 

—
Reply to this email directly or view it on GitHub
https://github.com/SoundControl/Issues/issues/75#issuecomment-25778921 .

**Comment by SoundControl** [comment]
Paul, I've not seen a new plus license from you. When do you plan on upgrading?

**Comment by nickelob** [comment]
Consider making it more clear that donating less than $3 will not grant Plus benefits.
