### ISSUE TITLE
"Hidden License" will not enable advanced features in Sound Control Plus..Help?

### ISSUE THREAD

**Issue by yads04** [SoundControl/Issues#78]
I purchased an upgrade to Sound Control Plus this AM and have not been successful enabling the services.  One page I came across indicated I have a "hidden License".

Not sure exactly what that means and also not sure where to enable the additional features. I checked for instructions in the extensions menu in Chrome, the website pages on Chrome Store, and throughout the extension's web pages but all I could find was a statement the features will turn on automatically after 5 minutes.  No such luck after 30 minutes now.  Can someone please assist me?

Thank you,

YADS04

**Comment by SoundControl** [comment]
I have followed up with this user privately
