### ISSUE TITLE
List Thumbs Up first in Chrome's keyboard shortcuts list

### ISSUE THREAD

**Issue by herstand** [SoundControl/Issues#81]
Since thumbs down is above thumbs up in Chrome's keyboard shortcuts list I accidentally set a shortcut for thumbs down that I thought would be for thumbs up (and subsequently killed a song I loved half-way through). Could you reorder them so thumbs up is above thumbs down (since visually up is above down).

Thanks!

<strong>Current list:</strong>

![current list](https://f.cloud.github.com/assets/950515/1545976/b920e946-4d7d-11e3-97fd-1d7d3968eb1d.png)

<strong>My preference:</strong>

![my preference](https://f.cloud.github.com/assets/950515/1545994/f5612e98-4d7d-11e3-913c-de2b3ae50fa3.png)

**Comment by SoundControl** [comment]
Unfortunately, the order is not configurable
