### ISSUE TITLE
Plus doesn't always work

### ISSUE THREAD

**Issue by Gilligan94** [SoundControl/Issues#83]
Every now and then youtube integration stops working and when I try to reenable it I get this message http://puu.sh/5oXrY/2474c4c4da.png this often persists for quite some time

**Comment by SoundControl** [comment]
It looks like your browser is not working correctly -- that image is not showing up correctly. What versions of Chrome and SoundControl are you using? Please send your license key to scott@soundcontrolplus.com so that I can follow up better (don't post it here)
