### ISSUE TITLE
Detachable Player

### ISSUE THREAD

**Issue by ghost** [SoundControl/Issues#86]
I have two suggetions both pertain to the mini player, Instead of leaving it attached to the actual soundcontrol button or have a button on it that detaches it from there so you can move it around and keep it open. And also add a way to open the player with a keyboard shortcut.

**Comment by SoundControl** [comment]
The player can already be opened with a keyboard shortcut.

The detachable player would be good.

**Comment by ghost** [comment]
O I didn't realize there was one. Sorry for not checking before hand on
that.

**Comment by SoundControl** [comment]
It can be confusing, because if you have the miniplayer set to 2 clicks on
the button then you also have to press the keyboard shortcut that many
times. There's no technical way around that. Let me know if that needs to
be made clearer somehow.

**Comment by ghost** [comment]
That's perfectly clear to me.
