### ISSUE TITLE
Plus not activating

### ISSUE THREAD

**Issue by megaroeny** [SoundControl/Issues#90]
I've used my account to activate Plus on 2 other computers, but its not working on mine at home.

My email is reonytonneyck@gmail.com. Please check what's wrong, thanks

**Comment by SoundControl** [comment]
You need only sign into Chrome. Settings > Sign into Chrome.

**Comment by megaroeny** [comment]
Yeah, I've been signed in. It's not working still

**Comment by SoundControl** [comment]
Did you turn off syncing of extensions?

Go to Options > "license" (lower right), copy the gray letters and numbers
in the lower left and email them to me at scott@soundcontrolplus.com.

**Comment by megaroeny** [comment]
No, Sync Everything is on.
