### ISSUE TITLE
SoundControl Plus on different computer

### ISSUE THREAD

**Issue by Mer0** [SoundControl/Issues#91]
I donated and got SoundControl Plus on my personal computer but when I went on my laptop, the SoundControl on my laptop stayed lite. I have my Gmail signed in for Chrome and everything. Does it mean I have to spend money everytime I use SoundControl on a different computer to get plus? Sorry for my bad English.

**Comment by SoundControl** [comment]
It will automatically sync. Confirm that you are using the same Google
account on both browsers at settings > sign in.
