### ISSUE TITLE
"Thanks for Installing" window always appears

### ISSUE THREAD

**Issue by rytoman** [SoundControl/Issues#92]
I hope this is a bug and not intentional, but every time I use SoundControl after closing Chrome or putting my computer to sleep, the window thanking me for installing SoundControl and advertising SoundControl Plus always opens up.  It's really annoying, and enough to cause me to uninstall if it is actually an intended behavior. Just wanted to let you know.

Regards

**Comment by SoundControl** [comment]
Sounds like this chrome bug:
https://github.com/SoundControl/Issues/issues/48

I suggest reinstalling chrome or deleting your profile data.
