### ISSUE TITLE
Spotify?

### ISSUE THREAD

**Issue by jawalther** [SoundControl/Issues#93]
I love SoundControl and want to upgrade to SoundControl plus but does it integrate with Spotify? If not, do you have plans to integrate with Spotify in the near future? Thanks and keep up the great work?

**Comment by SoundControl** [comment]
Last I checked, Spotify doesn't run in the browser

**Comment by jawalther** [comment]
try going to https://play.spotify.com/

**Comment by SoundControl** [comment]
It was broken for my spotify account, but worked when I created a new
account. Hmm. Looks possible. Do you know how long this player has been
available?

**Comment by jawalther** [comment]
I'm not sure how long the player has been around, sorry. I started using it a few weeks ago because it allows me to create and listen to my own playlists. Thanks!

**Comment by SoundControl** [comment]
This should be included when 1.6 is released
