### ISSUE TITLE
Songs playing get overlaped

### ISSUE THREAD

**Issue by theurso** [SoundControl/Issues#94]
A new song begins and is then played on top of the previous song.

**Comment by SoundControl** [comment]
I haven't encountered this in a while, but I have seen it. Still
inconclusive on what causes it. (Might be a pandora bug)

**Comment by jarquafelmu** [comment]
I see it sometimes with youtube but I don't know what causes it yet.

**Comment by SoundControl** [comment]
I haven't seen this in a long time. Closing unless more is seen.
