### ISSUE TITLE
When is SoundControl Plus activated after payment?

### ISSUE THREAD

**Issue by cablenator** [SoundControl/Issues#96]
I paid and got my receipt, but nothing in my email and I am still prompted to pay for the Plus features.

**Comment by SoundControl** [comment]
Please reply to me at scott@soundcontrolplus.com with the email address
that you used so that I can help you get everything working.

**Comment by cablenator** [comment]
Resolved in under an hour - either PayPal or LastPass or the page had a glitch that did not display the payment information on the second page.  Thanks!

**Comment by SoundControl** [comment]
Thanks!
