### ISSUE TITLE
Sound does not come back from an Ad to the same level it was before.

### ISSUE THREAD

**Issue by elyod72** [SoundControl/Issues#98]
I have my options in SoundControl set to play Ads at 10%. After the ad plays and Sound Control changes the audio level back, it does put it back to the level it was prior. It looks like no matter what it will set the level to about 25%.

**Comment by etramell** [comment]
I came here to report a similar issue:  I have SoundControl muting Pandora ads, and when the ad is over, my volume level is set very low, so I have to turn up the volume after each ad.

**Comment by SoundControl** [comment]
This is an intermittent issue that I am still working to determine the root
cause. (I have only experienced it once)

Any extra information could be helpful.
1) Are you on Windows, Mac, or Linux?
2) Do you have a separate adblocking extension?
3) Does the issue happen every time or only once in a while?
4) Anything particularly unique about your computer setup? (eg multiple
screens or chromebook?)

Thanks

**Comment by elyod72** [comment]
1) I am running a MacBook Pro 15" with OSX 10.8.5
2) I have no separate adblocking extensions.
3) I think it happens every time Pandora goes to a commercial and comes
back again. I will revisit the issue to confirm.
4) The only special setup I have is running two monitors and most of the
time Chrome is running on the second monitor. I will try it with Chrome on
the primary monitor and see if it still happens.

On Tue, Jan 21, 2014 at 1:31 PM, SoundControl notifications@github.comwrote:

> This is an intermittent issue that I am still working to determine the
> root
> cause. (I have only experienced it once)
> 
> Any extra information could be helpful.
> 1) Are you on Windows, Mac, or Linux?
> 2) Do you have a separate adblocking extension?
> 3) Does the issue happen every time or only once in a while?
> 4) Anything particularly unique about your computer setup? (eg multiple
> screens or chromebook?)
> 
> Thanks
> 
> On Tue, Jan 21, 2014 at 2:51 PM, etramell-tem notifications@github.comwrote:
> 
> > I came here to report a similar issue: I have SoundControl muting
> > Pandora
> > ads, and when the ad is over, my volume level is set very low, so I have
> > to
> > turn up the volume after each ad.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/SoundControl/Issues/issues/98#issuecomment-32961860>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/SoundControl/Issues/issues/98#issuecomment-32965781
> .

## 

Jim Tittle

**Comment by etramell** [comment]
1) I am running Windows 7.
2) I don't think I have any separate adblocking extensions.
3) This happens with every commercial that gets muted.
4) Just a plain old Dell Precision M6500.  Running from the built-in screen, no external monitor.

Other info:
- This has been happening for months, and Chrome just updates itself whenever it wants to, so I would say there is no specific version of Chrome to blame here.
- More detail on what happens:  I start up Pandora and set it to my desired volume.  It mutes when a commercial starts up, then unmutes when the commercial is over.  If I go look at your mini-player (I've got "click 1 time" set to "mini player") OR the Pandora tab itself, I see the volume handle near the very minimum edge of the slider.  So it's not just the audio changing without updating the player display -- something would appear to be actually setting the volume to some default level after the commercial is over.  (Of course, it could be that something is directly setting the volume, and the display is just reacting to some sort of "volume changed" event...)

Thanks for the quick response on this -- I use your extension for the very simplest of Pandora control, and this is the one thing that makes it not quite seamless.

I could run without muting ads for a while if you want me to confirm that it is actually the mute function that is causing this problem...  Let me know.

**Comment by elyod72** [comment]
I think I may have potentially found something interesting. I am testing
today. If I have the sound on Pandora's site up to full, when it comes back
from an ad, the volume is set to around 25%. However, if I have the volume
set to say 75%, when it comes back from an ad, it returns to the 75%.

Like I said, I'm testing today, I should be able to give you the results
later today.

On Tue, Jan 21, 2014 at 2:38 PM, etramell-tem notifications@github.comwrote:

> 1) I am running Windows 7.
> 2) I don't think I have any separate adblocking extensions.
> 3) This happens with every commercial that gets muted.
> 4) Just a plain old Dell Precision M6500. Running from the built-in
> screen, no external monitor.
> 
> Other info:
> 
>    -
> 
>    This has been happening for months, and Chrome just updates itself
>    whenever it wants to, so I would say there is no specific version of Chrome
>    to blame here.
>    -
> 
>    More detail on what happens: I start up Pandora and set it to my
>    desired volume. It mutes when a commercial starts up, then unmutes when the
>    commercial is over. If I go look at your mini-player (I've got "click 1
>    time" set to "mini player") OR the Pandora tab itself, I see the volume
>    handle near the very minimum edge of the slider. So it's not just the audio
>    changing without updating the player display -- something would appear to
>    be actually setting the volume to some default level after the commercial
>    is over. (Of course, it could be that something is directly setting the
>    volume, and the display is just reacting to some sort of "volume changed"
>    event...)
> 
> Thanks for the quick response on this -- I use your extension for the very
> simplest of Pandora control, and this is the one thing that makes it not
> quite seamless.
> 
> I could run without muting ads for a while if you want me to confirm that
> it is actually the mute function that is causing this problem... Let me
> know.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/SoundControl/Issues/issues/98#issuecomment-32972316
> .

## 

Jim Tittle

**Comment by etramell** [comment]
That is interesting.  Thanks for the update.

In case this information helps at all: I typically listen to Pandora at about 10% to 20%.  Definitely never anywhere near 50% or beyond.

**Comment by SoundControl** [comment]
A question for both of you:

1) When you set the volume to 0%, 50%, 100% does the volume control in the
miniplayer always match the value in the pandora tab?
1a) Try using the miniplayer to set the volume and check the tab
1b) Try using the tab to set the volume and check the miniplayer

Thanks!

**Comment by elyod72** [comment]
The volume on Pandora's site was set to 75%. In the miniplayer I moved it
up to 100%. The volume instantly dropped to about 25%. NOT the 100% I put
it at.

On Thu, Jan 23, 2014 at 7:12 AM, SoundControl notifications@github.comwrote:

> A question for both of you:
> 
> 1) When you set the volume to 0%, 50%, 100% does the volume control in the
> miniplayer always match the value in the pandora tab?
> 1a) Try using the miniplayer to set the volume and check the tab
> 1b) Try using the tab to set the volume and check the miniplayer
> 
> Thanks!
> 
> On Thu, Jan 23, 2014 at 9:08 AM, etramell-tem notifications@github.comwrote:
> 
> > That is interesting. Thanks for the update.
> > 
> > In case this information helps at all: I typically listen to Pandora at
> > about 10% to 20%. Definitely never anywhere near 50% or beyond.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/SoundControl/Issues/issues/98#issuecomment-33131422>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/SoundControl/Issues/issues/98#issuecomment-33131788
> .

## 

Jim Tittle

**Comment by elyod72** [comment]
Now I can't seem to get it to do it. The miniplayer sound control now seems
to be tracking with the website's one. I can't seem to reproduce the issue
with any consistency.

I am a software engineer myself and inconsistent bugs has got to be the
most frustrating things to track down.

On Thu, Jan 23, 2014 at 7:19 AM, Jim Tittle elyod72@gmail.com wrote:

> The volume on Pandora's site was set to 75%. In the miniplayer I moved it
> up to 100%. The volume instantly dropped to about 25%. NOT the 100% I put
> it at.
> 
> On Thu, Jan 23, 2014 at 7:12 AM, SoundControl notifications@github.comwrote:
> 
> > A question for both of you:
> > 
> > 1) When you set the volume to 0%, 50%, 100% does the volume control in
> > the
> > miniplayer always match the value in the pandora tab?
> > 1a) Try using the miniplayer to set the volume and check the tab
> > 1b) Try using the tab to set the volume and check the miniplayer
> > 
> > Thanks!
> > 
> > On Thu, Jan 23, 2014 at 9:08 AM, etramell-tem notifications@github.comwrote:
> > 
> > > That is interesting. Thanks for the update.
> > > 
> > > In case this information helps at all: I typically listen to Pandora at
> > > about 10% to 20%. Definitely never anywhere near 50% or beyond.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/SoundControl/Issues/issues/98#issuecomment-33131422>
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/SoundControl/Issues/issues/98#issuecomment-33131788
> > .
> 
> ## 
> 
> Jim Tittle

## 

Jim Tittle

**Comment by etramell** [comment]
I did the requested testing and found that the miniplayer volume control is tracking exactly with the Pandora page, no matter what volume I set it at.  I changed volumes in both places for a few minutes and never saw a discrepancy between the two.

I did notice two slight issues (which I wouldn't mention except I'm also a software engineer and sometimes the weirdest hints are helpful):
- The miniplayer's handle jumps to where you click on the track, and then shifts to the left a few pixels every time.
- The miniplayer has a nice (standard, I'd say) mute function when you click the sound icon.  Clicking Pandora's sound icon only shows/hides the volume track.

Also, while I was typing this, there was a short silence (which I assume was an ad, but I didn't look), and the next song played at the original volume.  (I also noticed a "thanks for installing SoundControl" dialog -- have you pushed an update today?)

**Comment by etramell** [comment]
![image](https://f.cloud.github.com/assets/1588343/1987199/34168b74-8456-11e3-9a07-6187c8b158f7.png)
![image](https://f.cloud.github.com/assets/1588343/1987203/4495e7ec-8456-11e3-99cd-2f0fbd968b45.png)

More data...  The commercial mute volume change just happened again.  I have pasted screenshots of the miniplayer.  One with the volume right after the unmute (which is not quite zero, but not much more), and one with the volume after I put it back to where I had it.

**Comment by SoundControl** [comment]
I think I've found the culprit! I expect this issue to be fixed when 1.6 is released. Please let me know if you observe it after the update.

**Comment by etramell** [comment]
1.6 showed up last night sometime, so I was able to run it for several hours today.

Looks like you have killed the bug.  Several commercials came and went.  All were properly muted, and the next song played at the correct volume every time.  I didn't have to adjust the player volume even once.  After a while, I stopped noticing the commercial breaks altogether.

Thanks very much for the fix!  This is very helpful -- now I can stay "in the zone" instead of fiddling with the music volume all day.

**Comment by elyod72** [comment]
It seems to have fixed the problem for me too. I listened all day yesterday
without any problems.

Thanks so much!

On Thu, Jan 30, 2014 at 3:02 PM, etramell-tem notifications@github.comwrote:

> 1.6 showed up last night sometime, so I was able to run it for several
> hours today.
> 
> Looks like you have killed the bug. Several commercials came and went. All
> were properly muted, and the next song played at the correct volume every
> time. I didn't have to adjust the player volume even once. After a while, I
> stopped noticing the commercial breaks altogether.
> 
> Thanks very much for the fix! This is very helpful -- now I can stay "in
> the zone" instead of fiddling with the music volume all day.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/SoundControl/Issues/issues/98#issuecomment-33744597
> .

## 

Jim Tittle
